type CardBase={name:string;meaning_up:string;meaning_rev:string};
export type CardJa=CardBase&{emoji:string};

const TAROT_JA:Record<string,CardBase>={
  'The Fool': { name: '愚者', meaning_up: '新しい出発・無限の可能性', meaning_rev: '無謀・不注意・軽率' },
  'The Magician': { name: '魔術師', meaning_up: '意志力・スキル・自信', meaning_rev: '操作・技術の悪用' },
  'The High Priestess': { name: '女教皇', meaning_up: '直感・神秘・内なる知恵', meaning_rev: '秘密・表面的な知識' },
  'The Empress': { name: '女帝', meaning_up: '豊かさ・母性・創造', meaning_rev: '依存・過保護' },
  'The Emperor': { name: '皇帝', meaning_up: '権威・安定・リーダーシップ', meaning_rev: '支配欲・硬直' },
  'The Hierophant': { name: '法王', meaning_up: '伝統・精神的指導・慣習', meaning_rev: '反抗・型破り' },
  'The Lovers': { name: '恋人', meaning_up: '愛・調和・選択', meaning_rev: '失調・価値観の対立' },
  'The Chariot': { name: '戦車', meaning_up: '勝利・意志力・前進', meaning_rev: '攻撃性・方向性の欠如' },
  'Strength': { name: '力', meaning_up: '勇気・忍耐・内なる強さ', meaning_rev: '弱さ・自己疑念' },
  'The Hermit': { name: '隠者', meaning_up: '内省・孤独・内なる導き', meaning_rev: '孤立・頑固' },
  'Wheel of Fortune': { name: '運命の輪', meaning_up: '運命・チャンス・転機', meaning_rev: '不運・変化への抵抗' },
  'Justice': { name: '正義', meaning_up: '公正・真実・因果応報', meaning_rev: '不公正・不誠実' },
  'The Hanged Man': { name: '吊られた男', meaning_up: '忍耐・新視点・犠牲', meaning_rev: '停滞・無駄な犠牲' },
  'Death': { name: '死神', meaning_up: '変容・終わりと始まり', meaning_rev: '変化への抵抗・停滞' },
  'Temperance': { name: '節制', meaning_up: 'バランス・節制・調和', meaning_rev: '過剰・不均衡' },
  'The Devil': { name: '悪魔', meaning_up: '束縛・執着・誘惑', meaning_rev: '解放・自由への一歩' },
  'The Tower': { name: '塔', meaning_up: '突然の変化・崩壊・啓示', meaning_rev: '変化回避・内なる崩壊' },
  'The Star': { name: '星', meaning_up: '希望・癒し・インスピレーション', meaning_rev: '失望・絶望' },
  'The Moon': { name: '月', meaning_up: '幻想・潜在意識・不安', meaning_rev: '混乱の解消・真実' },
  'The Sun': { name: '太陽', meaning_up: '成功・喜び・活力', meaning_rev: '悲観・過信' },
  'Judgement': { name: '審判', meaning_up: '覚醒・再生・過去の清算', meaning_rev: '自己批判・停滞' },
  'The World': { name: '世界', meaning_up: '完成・達成・統合', meaning_rev: '未完・停滞' },
  'Ace of Wands': { name: 'ワンドのエース', meaning_up: '新しい情熱・出発点', meaning_rev: '遅延・エネルギー不足' },
  'Two of Wands': { name: 'ワンドの2', meaning_up: '計画・未来を見据える', meaning_rev: '決断できない・内向き' },
  'Three of Wands': { name: 'ワンドの3', meaning_up: '前進・探求・成長', meaning_rev: '遅延・見通しの甘さ' },
  'Four of Wands': { name: 'ワンドの4', meaning_up: '祝福・安定・家族の喜び', meaning_rev: '転落・不安定' },
  'Five of Wands': { name: 'ワンドの5', meaning_up: '競争・葛藤・挑戦', meaning_rev: '意見の衝突・混乱' },
  'Six of Wands': { name: 'ワンドの6', meaning_up: '勝利・認められる・凱旋', meaning_rev: '傲慢・自信の欠如' },
  'Seven of Wands': { name: 'ワンドの7', meaning_up: '守り・粘り強さ', meaning_rev: '防御姿勢・疲弊' },
  'Eight of Wands': { name: 'ワンドの8', meaning_up: 'スピード・急展開', meaning_rev: '遅延・焦り・障害' },
  'Nine of Wands': { name: 'ワンドの9', meaning_up: '回復力・粘り・準備', meaning_rev: '疲弊・放棄' },
  'Ten of Wands': { name: 'ワンドの10', meaning_up: '重荷・責任・忍耐', meaning_rev: '過剰な負担・手放し' },
  'Page of Wands': { name: 'ワンドのペイジ', meaning_up: '熱意・創造・新しいアイデア', meaning_rev: '空回り・無謀' },
  'Knight of Wands': { name: 'ワンドのナイト', meaning_up: 'エネルギー・勇気・行動力', meaning_rev: '衝動的・無鉄砲' },
  'Queen of Wands': { name: 'ワンドのクイーン', meaning_up: '自信・魅力・リーダーシップ', meaning_rev: '意地悪・嫉妬' },
  'King of Wands': { name: 'ワンドのキング', meaning_up: 'ビジョン・カリスマ・起業家精神', meaning_rev: '横暴・衝動的' },
  'Ace of Cups': { name: 'カップのエース', meaning_up: '愛の始まり・感情の豊かさ', meaning_rev: '感情の封印・失恋' },
  'Two of Cups': { name: 'カップの2', meaning_up: 'パートナーシップ・愛情・調和', meaning_rev: '関係の崩壊・不調和' },
  'Three of Cups': { name: 'カップの3', meaning_up: '友情・祝福・喜び', meaning_rev: '過剰な享楽・三角関係' },
  'Four of Cups': { name: 'カップの4', meaning_up: '内省・再考・新たな視点', meaning_rev: '機会を逃す・退屈' },
  'Five of Cups': { name: 'カップの5', meaning_up: '喪失・後悔・悲しみ', meaning_rev: '受け入れ・立ち直り' },
  'Six of Cups': { name: 'カップの6', meaning_up: '懐かしさ・過去・無邪気な喜び', meaning_rev: '過去への執着' },
  'Seven of Cups': { name: 'カップの7', meaning_up: '幻想・選択肢・空想', meaning_rev: '幻想から覚める・明確な目標' },
  'Eight of Cups': { name: 'カップの8', meaning_up: '手放し・旅立ち・新展開', meaning_rev: '諦め・停滞' },
  'Nine of Cups': { name: 'カップの9', meaning_up: '満足・願望成就・幸福', meaning_rev: '欲張り・不満足' },
  'Ten of Cups': { name: 'カップの10', meaning_up: '家族の幸せ・完全な調和', meaning_rev: '家庭の不和・不満' },
  'Page of Cups': { name: 'カップのペイジ', meaning_up: '直感・メッセージ・感受性', meaning_rev: '感情の揺れ・未熟' },
  'Knight of Cups': { name: 'カップのナイト', meaning_up: 'ロマンス・魅力・理想主義', meaning_rev: '気まぐれ・感情的' },
  'Queen of Cups': { name: 'カップのクイーン', meaning_up: '共感・思いやり・情緒の安定', meaning_rev: '感情的不安定・依存' },
  'King of Cups': { name: 'カップのキング', meaning_up: '感情の成熟・知恵・寛大さ', meaning_rev: '感情操作・不安定' },
  'Ace of Swords': { name: 'ソードのエース', meaning_up: '真実・明晰な思考・突破', meaning_rev: '混乱・誤解' },
  'Two of Swords': { name: 'ソードの2', meaning_up: '均衡・決断の保留・岐路', meaning_rev: '板挟み・混乱' },
  'Three of Swords': { name: 'ソードの3', meaning_up: '悲しみ・失望・痛みを受け入れる', meaning_rev: '回復・許し' },
  'Four of Swords': { name: 'ソードの4', meaning_up: '休息・回復・静養', meaning_rev: '停滞・病' },
  'Five of Swords': { name: 'ソードの5', meaning_up: '葛藤・勝利の代償・喧嘩', meaning_rev: '和解・損失の受け入れ' },
  'Six of Swords': { name: 'ソードの6', meaning_up: '移行・安定へ向かう旅', meaning_rev: '出口なし・停滞' },
  'Seven of Swords': { name: 'ソードの7', meaning_up: '策略・計画的行動・単独行動', meaning_rev: '発覚・無謀な計画' },
  'Eight of Swords': { name: 'ソードの8', meaning_up: '制限・恐怖・思い込み', meaning_rev: '束縛からの解放' },
  'Nine of Swords': { name: 'ソードの9', meaning_up: '不安・悪夢・心配', meaning_rev: '立ち直り・希望の光' },
  'Ten of Swords': { name: 'ソードの10', meaning_up: '終わり・裏切り・底打ち', meaning_rev: '回復・新しいサイクル' },
  'Page of Swords': { name: 'ソードのペイジ', meaning_up: '好奇心・情報収集・鋭い観察力', meaning_rev: '噂・スパイ行為' },
  'Knight of Swords': { name: 'ソードのナイト', meaning_up: '果敢・直進・知的行動', meaning_rev: '衝動的・残忍' },
  'Queen of Swords': { name: 'ソードのクイーン', meaning_up: '独立・明晰・客観的判断', meaning_rev: '冷酷・孤立' },
  'King of Swords': { name: 'ソードのキング', meaning_up: '知性・権威・論理的判断', meaning_rev: '独裁・残酷' },
  'Ace of Pentacles': { name: 'ペンタクルのエース', meaning_up: '物質的豊かさ・新しいチャンス', meaning_rev: '逃したチャンス・損失' },
  'Two of Pentacles': { name: 'ペンタクルの2', meaning_up: 'バランス・適応力・柔軟性', meaning_rev: '乱雑・混乱' },
  'Three of Pentacles': { name: 'ペンタクルの3', meaning_up: 'チームワーク・スキル・達成', meaning_rev: '不調和・技術不足' },
  'Four of Pentacles': { name: 'ペンタクルの4', meaning_up: '安定・貯蓄・保守的', meaning_rev: '財産の喪失・けち' },
  'Five of Pentacles': { name: 'ペンタクルの5', meaning_up: '困窮・孤立・物質的困難', meaning_rev: '回復・支援を求める' },
  'Six of Pentacles': { name: 'ペンタクルの6', meaning_up: '寛大さ・分かち合い・贈り物', meaning_rev: '貸し借り・不均衡' },
  'Seven of Pentacles': { name: 'ペンタクルの7', meaning_up: '忍耐・長期計画・評価', meaning_rev: '苛立ち・方向転換' },
  'Eight of Pentacles': { name: 'ペンタクルの8', meaning_up: '勤勉・技術向上・職人気質', meaning_rev: '怠慢・質の低下' },
  'Nine of Pentacles': { name: 'ペンタクルの9', meaning_up: '豊かさ・自立・達成感', meaning_rev: '物質主義・孤独' },
  'Ten of Pentacles': { name: 'ペンタクルの10', meaning_up: '家族の繁栄・遺産・安定', meaning_rev: '財政問題・家族の不和' },
  'Page of Pentacles': { name: 'ペンタクルのペイジ', meaning_up: '向上心・学習・実践的', meaning_rev: '無謀・怠惰' },
  'Knight of Pentacles': { name: 'ペンタクルのナイト', meaning_up: '堅実・忍耐・着実な前進', meaning_rev: '停滞・頑固' },
  'Queen of Pentacles': { name: 'ペンタクルのクイーン', meaning_up: '豊かさ・現実的・母性的', meaning_rev: '不安・嫉妬' },
  'King of Pentacles': { name: 'ペンタクルのキング', meaning_up: '繁栄・ビジネス・安定した成功', meaning_rev: '財産の喪失・頑固' },
};

function getEmoji(jaName:string):string{
  const major:Record<string,string>={
    '愚者':'🃏',
    '魔術師':'✨',
    '女教皇':'🌙',
    '女帝':'🌸',
    '皇帝':'👑',
    '法王':'⛪',
    '恋人':'💕',
    '戦車':'⚡',
    '力':'🦁',
    '隠者':'🕯️',
    '運命の輪':'🎡',
    '正義':'⚖️',
    '吊られた男':'🔄',
    '死神':'🦋',
    '節制':'🌈',
    '悪魔':'🔗',
    '塔':'🌩️',
    '星':'⭐',
    '月':'🌙',
    '太陽':'☀️',
    '審判':'🎺',
    '世界':'🌍',
  };
  if(major[jaName])return major[jaName];
  if(jaName.includes('ワンド'))return '🔥';
  if(jaName.includes('カップ'))return '💧';
  if(jaName.includes('ソード'))return '⚔️';
  if(jaName.includes('ペンタクル'))return '🌿';
  return '🔮';
}

export function translateTarotCard(name:string):CardJa{
  const base=TAROT_JA[name]??{name,meaning_up:'（翻訳なし）',meaning_rev:'（翻訳なし）'};
  return {...base,emoji:getEmoji(base.name)};
}